using UnityEngine;

public class Checkpoint : MonoBehaviour {
    private Vector3 lastCheckpointPosition; // Guarda la √∫ltima posici√≥n del checkpoint alcanzado
    private bool PlayerDentro = false; // Verifica si el jugador est√° dentro del √°rea

    private void OnTriggerEnter(Collider other) {
        if (other.CompareTag("Player")) {
            PlayerDentro = true; // Activa la detecci√≥n cuando el jugador entra
            Debug.Log("üîπ Presiona 'E' para guardar el checkpoint.");
        }
    }

    private void OnTriggerExit(Collider other) {
        if (other.CompareTag("Player")) {
            PlayerDentro = false; // Desactiva la detecci√≥n cuando el jugador sale
        }
    }

    private void Update() {
        if (PlayerDentro && Input.GetKeyDown(KeyCode.E)) {
            int items = GameManager.Instance != null ? GameManager.Instance.collectedItems : 0;
            SaveSystem.SaveGame(transform.position, items, "mesi");
            lastCheckpointPosition = transform.position; // Guarda la posici√≥n del checkpoint
            Debug.Log("‚úÖ Partida guardada en el checkpoint.");
        }

        if (Input.GetKeyDown(KeyCode.L)) {
            if (lastCheckpointPosition != Vector3.zero) {
                GameObject Player = GameObject.FindGameObjectWithTag("Player");
                if (Player != null) {
                    Player.transform.position = lastCheckpointPosition;
                    Debug.Log("üöÄ Teletransportado al √∫ltimo checkpoint guardado.");
                }
            } else {
                Debug.Log("‚ö†Ô∏è No hay ning√∫n checkpoint guardado a√∫n.");
            }
        }
    }
}
